name: Test Project
on: push
jobs:
  test:
    runs-on: ubuntu_latest
    steps:
      - name: Get code
        uses: actions/checkout@v5
      - name: Install NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci # install dependencies with versions, specified in package-lock
      - name: Run tests
        run: npm test

